services:
  admin-panel-server:
    build: ./server
    container_name: panel_server
    networks:
      - bot_services
    volumes:
      - ./server/uploads:/uploads
    environment:
      TZ: Asia/Tashkent
      POSTGRES_URL: host=postgres user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB port=$POSTGRES_INNER_PORT sslmode=disable
      REDIS_PORT: $REDIS_PORT
      BOT_TOKEN: $BOT_TOKEN
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_TTL: $REDIS_TTL
      HTTP_SERVER_PORT: $HTTP_SERVER_PORT
      SSE_TTL: $SSE_TTL
      TG_API_URL: $TG_API_URL
      JWT_SECRET_TTL: $JWT_SECRET_TTL
      JWT_SECRET: $JWT_SECRET
      GRPC_ADDR: $GRPC_HOST:$GRPC_PORT
      ALLOW_ORIGINS: $ALLOW_ORIGINS
    ports:
      - "127.0.0.1:$HTTP_SERVER_PORT:$HTTP_SERVER_PORT"

volumes:
  uploads:

networks:
  bot_services:
    external: true
